### ISSUE TITLE
Implement Automatic Deployment on Successful Pipeline Completion

### ISSUE THREAD

**Issue by ktenman** [ktenman/portfolio#23]
## Background
Our current CI/CD pipeline builds and tests the application but requires manual intervention for deployment. We want to automate this process while ensuring that deployments aren't triggered by Dependabot merges.

## Objective
Implement an automatic deployment step in our CI/CD pipeline that triggers when all tests pass and the merge is not from Dependabot.

### 1. Pipeline Configuration
- [ ] Identify the current pipeline stages (e.g., build, test, etc.)
- [ ] Add a new deployment stage to the pipeline

### 2. Deployment Script
- [ ] Create a deployment script that handles the actual deployment process
- [ ] Ensure the script includes necessary checks and failsafes

### 3. Conditional Logic
- [ ] Implement logic to check if the merge is from Dependabot
- [ ] Add condition to trigger deployment only for non-Dependabot merges

### 4. Environment Configuration
- [ ] Set up necessary environment variables for deployment (e.g., server credentials)
- [ ] Ensure these variables are securely stored and accessed

### 5. Testing
- [ ] Create test scenarios to verify the automatic deployment
- [ ] Test the Dependabot merge exclusion logic

### 6. Monitoring and Logging
- [ ] Add logging to the deployment process
- [ ] Set up alerts for successful/failed deployments

### 7. Rollback Procedure
- [ ] Implement an automated rollback procedure in case of deployment failure

### 8. Documentation
- [ ] Update CI/CD documentation to reflect the new automatic deployment process
- [ ] Document the deployment and rollback procedures

## Acceptance Criteria
- [ ] Successful merges to the main branch that pass all tests trigger an automatic deployment
- [ ] Merges from Dependabot do not trigger automatic deployment
- [ ] The deployment process is fully logged and monitored
- [ ] A rollback procedure is in place and documented
- [ ] The team is notified of successful/failed deployments

## Implementation Details
Here's a pseudo-code example of how the conditional deployment might look in a GitHub Actions workflow:

```yaml
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test

  deploy:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to production
        run: ./deploy.sh
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
```

## Additional Considerations
- Consider implementing a staging deployment before production
- Evaluate the need for manual approval for production deployments
- Ensure the deployment process is idempotent
- Consider implementing feature flags for safer deployments

## Resources
- [GitHub Actions Documentation](https://docs.github.com/en/actions)
- [Continuous Deployment Strategies](https://www.atlassian.com/continuous-delivery/continuous-deployment/deployment-strategies)

## Estimated Time
- Pipeline configuration: 1 day
- Deployment script creation: 1-2 days
- Conditional logic implementation: 1 day
- Environment setup: 1 day
- Testing: 1-2 days
- Monitoring and logging setup: 1 day
- Rollback procedure implementation: 1 day
- Documentation: 1 day

Total: 8-10 days
